version: "3.7"

services:
  database:
    image: mysql:latest
    environment:  # 환경변수
      MYSQL_ROOT_PASSWORD: books!234
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
    platform: linux/x86_64 # m1인 경우
    ports:
      - "3306:3306"
    container_name: db-container
    restart: always
    networks:
      - books-network

  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      DB_HOST: db-container
      DB_PORT: 3306
      DATABASE_NAME: books
      DB_USERNAME: booksuser
      DB_PASSWORD: books!234
    container_name: app
    restart: always
    networks:
      - books-network


networks:
  books-network: