spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false


jwt:
  token-secret: YXZhdGFydHJpcGF1dGhvcml6YXRpb25qd3RtYW5hZ2VzZWNyZXRrZXkK
  expired-in: 600000 # 10 min